### ISSUE TITLE
Docker frontend crashing

### ISSUE THREAD

**Issue by mind-overflow** [PckdHQ/Pckd#34]
Using either the latest docker image or building it myself, I get this error:

```
frontend_1  | 2022/06/04 12:57:12 [emerg] 1#1: no host in upstream ":4000" in /etc/nginx/conf.d/default.conf:16
frontend_1  | nginx: [emerg] no host in upstream ":4000" in /etc/nginx/conf.d/default.conf:16
frontend_1  | Starting NGINX...
pckd-url-shortener_frontend_1 exited with code 1
```

Which makes Pckd unreachable from the web.

**Comment by Tan-ki** [comment]
Make sure you've set the env variable "BACKEND_URL" in your front container, it should fix the "nginx: [emerg] no host in upstream ":4000"" error.
