### ISSUE TITLE
github demo not working

### ISSUE THREAD

**Issue by hemcharan22** [PckdHQ/Pckd#54]
https://pckd.me/github-demo - not working

error: 502 Bad Gateway
os: Linux

![image](https://user-images.githubusercontent.com/77770865/184477603-0f8d8d14-db80-4542-956e-39248ef98992.png)

**Comment by Just-Moh-it** [comment]
Hey, it frequently goes down due to issues with PM2 and doesn't start again for some reason, so I manually have to restart it... I did it, so it should work. Though I'll try to automate this through a cron job sometimes soon
