### ISSUE TITLE
White screen On firsrt  

### ISSUE THREAD

**Issue by Noritem-Dev** [PckdHQ/Pckd#56]
I try to use it the first time

and it shows only this: 

![image](https://user-images.githubusercontent.com/71951392/184508137-ec5eb700-933a-447e-935b-085885c2dd24.png)

**Comment by Just-Moh-it** [comment]
This is a bug with building the app that happens very unexpectedly. The only solution for now is to rebuild the client 😞 

(Since we're already working on a V2 with a totally different codebase, V1 issues are de-prioritized right now)
