### ISSUE TITLE
Website 502s

### ISSUE THREAD

**Issue by TheOnlyWayUp** [PckdHQ/Pckd#61]
https://pckd.me -> 502

![image](https://user-images.githubusercontent.com/76237496/190226488-f8b2e9bc-42d6-4ab3-882e-c0081ec2d056.png)

**Comment by nkwsy** [comment]
Still down :(

**Comment by Just-Moh-it** [comment]
@nkwsy @TheOnlyWayUp this might be working right now. PM2 randomly crashes the application and I have to manually restart it occasionally. I'll look into more long-term and resilient hosting solutions shortly.
